project:
  type: website

website:
  title: "Housing Prices"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model.qmd
      - href: sources.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



