project:
  type: website

website:
  title: "Housing Prices"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model.qmd
      - text: Sources
        menu:
          - href: sources-1.qmd
            text: sources 1
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



